src/Entity/CartContents.php
<?php

namespace App\Entity;

use App\Repository\CartContentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartContentsRepository::class)]
class CartContents
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Quantity = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\ManyToOne(inversedBy: 'cartContents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    #[ORM\ManyToOne(inversedBy: 'cartContents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cart $cart = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }
}

src/Controller/CartContentsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartContentsController extends AbstractController
{
    #[Route('/cart/contents', name: 'app_cart_contents')]
    public function index(): Response
    {
        //Afficher les achats de l'utilisateur
        $user = $this->getUser();
        $cart = $user->getCart();
        $cartItems = $cart->getCartItems();

        return $this->render('cart_contents/index.html.twig', [
            'cartItems' => $cartItems,
        ]);
    }
}

templates/cart_contents/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartContentsController!
{% endblock %}

{% block body %}

	<h1>Vos achats commandés</h1>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Produit</th>
				<th>Quantité</th>
				<th>Prix</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for cartContent in cartContents %}
				<tr>
					<td>{{ cartContent.id }}</td>
					<td>{{ cartContent.product.name }}</td>
					<td>{{ cartContent.quantity }}</td>
					<td>{{ cartContent.product.price }}</td>
					<td>
						<a href="{{ path('cart_contents_show', {'id': cartContent.id}) }}">show</a>
						<a href="{{ path('cart_contents_edit', {'id': cartContent.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="8">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}